---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ephemeral.ephemeralenv.io
  resources:
  - environmenttemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ephemeral.ephemeralenv.io
  resources:
  - environmenttemplates/status
  - ephemeralenvs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ephemeral.ephemeralenv.io
  resources:
  - ephemeralenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ephemeral.ephemeralenv.io
  resources:
  - ephemeralenvs/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  - referencegrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
